title: Git Workshop
description: Using git to build software
theme: just-the-docs

url: https://tonyburwinkel.github.io

aux_links:
  Useful Links: https://github.com/just-the-docs/just-the-docs-template

color_scheme: dark